version: '3.1'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./public:/usr/src/app
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '8002:80'
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    user: '1000:1000'
  db:
    image: mysql:5.7
    volumes:
      - .docker/mysql/data:/var/lib/mysql
      - .docker/mysql/dumps:/usr/app/dumps/
    restart: unless-stopped
    env_file:
      - .env
    user: '1000:1000'
    ports:
      - '3306:3306'